sudo: enabled
language: python
python:
  - "3.6"

before_install: 
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build

script: 
  - docker-compose up -d
  - sleep 10
  - docker-compose run web coverage run --source=. manage.py test
  - docker-compose run web coverage report

after_success:
  - docker-compose run web coveralls

before_deploy:
  - echo "${DOCKER_HUB_PASSWORD}" | docker login --username "${DOCKER_HUB_USER}" --password-stdin
  - sudo git stash --all

deploy:
  provider: script
  script: docker push felipe72/gamesbi-crossdata
  on:
    branch: dockerhub_test

